[loggers]
keys=root,setup,localhandler,virtualnet,programhandler,localclient,xio,capture,xenon_code,xenon_benchmarks,xenon_network,xenon_estimation_functions,xenon

[handlers]
keys=consoleHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=WARNING
handlers=consoleHandler

[logger_setup]
level=INFO
qualname=Setup
handlers=consoleHandler
propagate=0

[logger_internalcli]
level=DEBUG
qualname=InternalCLI
handlers=consoleHandler
propagate=0

[logger_localhandler]
level=INFO
qualname=Local Handler
handlers=consoleHandler
propagate=0

[logger_virtualnet]
level=WARNING
qualname=Virtual Network
handlers=consoleHandler
propagate=0

[logger_programhandler]
level=WARNING
qualname=Program Handler
handlers=consoleHandler
propagate=0

[logger_localclient]
level=INFO
qualname=Local Client
handlers=consoleHandler
propagate=0

[logger_xio]
level=WARNING
qualname=XIO
handlers=consoleHandler
propagate=0

[logger_capture]
level=INFO
qualname=Capture
handlers=consoleHandler
propagate=0

[logger_xenon_code]
level=INFO
qualname=XENON Code Generation
handlers=consoleHandler
propagate=0

[logger_xenon_benchmarks]
level=WARNING
qualname=XENON Benchmarks
handlers=consoleHandler
propagate=0

[logger_xenon_network]
level=INFO
qualname=XENON Network Model
handlers=consoleHandler
propagate=0

[logger_xenon_estimation_functions]
level=INFO
qualname=XENON Estimation Functions
handlers=consoleHandler
propagate=0

[logger_xenon]
level=INFO
qualname=XENON
handlers=consoleHandler
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=simpleFormatter
args=(sys.stdout,)

#[handler_fileHandler]
#class=FileHandler
#level=DEBUG
#formatter=fileFormatter
#args=('%(logfilename)s',)

[formatter_simpleFormatter]
#format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
format=%(levelname)s (%(name)s): %(message)s
datefmt=
